service: aws-fivetran-connector-template

frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.6

functions:
  aws-fivetran-connector:
    handler: handler.lambda_handler

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    pythonBin: python3
    dockerizePip: False
