name: deploy lambda functions

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy_serverless:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: clone local repository
        uses: actions/checkout@v2
      - name: npm install
        run: npm install
      - name: serverless
        run: npm install serverless
      - name: deploy
        uses: serverless/github-action@v3.1
        with:
          args: --stage prod deploy
