name: deploy lambda functions

on:
  push:
    branches:
      - master
      
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1

jobs:
  deploy_serverless:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.0]
    steps:
      - name: clone local repository
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
           node-version: ${{ matrix.node-version }}
      - name: clean cache npm
        run: npm cache clean --force
      - name: npm install
        run: npm install
      - name: install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: install serverless
        run: npm install -g serverless
      - name: serverless config
        uses: serverless/github-action@v3.1
        with:
          args: config credentials --provider aws --key ${{ env.AWS_ACCESS_KEY_ID }} --secret ${{ env.AWS_SECRET_ACCESS_KEY }}  --profile serverless-admin
      - name: Serverless install Plugin 
        uses: serverless/github-action@v3.1
        with:
          args: plugin install -n serverless-python-requirements       
      - name: serverless deploy
        uses: serverless/github-action@v3.1
        with:
          args: deploy --aws-profile serverless-admin --region us-west-2 --stage prod



 

